### ISSUE TITLE
Compilation failure on Ubuntu Server 15

### ISSUE THREAD

**Issue by grayfall** [bioinf/Sibelia#172]
```
$:~/.local/opt$ wget https://github.com/bioinf/Sibelia/archive/v3.0.5.tar.gz
--2016-04-27 20:32:13--  https://github.com/bioinf/Sibelia/archive/v3.0.5.tar.gz
Resolving github.com (github.com)... 192.30.252.128
Connecting to github.com (github.com)|192.30.252.128|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/bioinf/Sibelia/tar.gz/v3.0.5 [following]
--2016-04-27 20:32:14--  https://codeload.github.com/bioinf/Sibelia/tar.gz/v3.0.5
Resolving codeload.github.com (codeload.github.com)... 192.30.252.162
Connecting to codeload.github.com (codeload.github.com)|192.30.252.162|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘v3.0.5.tar.gz’

v3.0.5.tar.gz                     [   <=>                                              ]  28.43M   688KB/s   in 45s    

2016-04-27 20:33:00 (654 KB/s) - ‘v3.0.5.tar.gz’ saved [29809395]

$:~/.local/opt$ tar -xzf v3.0.5.tar.gz 
$:~/.local/opt$ cd Sibelia-3.0.5/build/
$:~/.local/opt/Sibelia-3.0.5/build$ cmake ../src -DCMAKE_INSTALL_PREFIX=~/.local/opt/Sibelia
-- The CXX compiler identification is GNU 5.2.1
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The C compiler identification is GNU 5.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test HAVE_GCC_WALL
-- Performing Test HAVE_GCC_WALL - Success
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER
-- Performing Test HAVE_GCC_FOMIT_FRAME_POINTER - Success
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Performing Test HAVE_INLINE
-- Performing Test HAVE_INLINE - Success
-- Performing Test HAVE___INLINE
-- Performing Test HAVE___INLINE - Success
-- Performing Test HAVE___INLINE__
-- Performing Test HAVE___INLINE__ - Success
-- Performing Test HAVE___DECLSPEC_DLLEXPORT_
-- Performing Test HAVE___DECLSPEC_DLLEXPORT_ - Failed
-- Performing Test HAVE___DECLSPEC_DLLIMPORT_
-- Performing Test HAVE___DECLSPEC_DLLIMPORT_ - Failed
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Looking for PRId32
-- Looking for PRId32 - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/assemblers/.local/opt/Sibelia-3.0.5/build
$:~/.local/opt/Sibelia-3.0.5/build$ make
Scanning dependencies of target divsufsort
[  3%] Building C object libdivsufsort-2.0.1/lib/CMakeFiles/divsufsort.dir/divsufsort.o
[  6%] Building C object libdivsufsort-2.0.1/lib/CMakeFiles/divsufsort.dir/sssort.o
[  9%] Building C object libdivsufsort-2.0.1/lib/CMakeFiles/divsufsort.dir/trsort.o
[ 12%] Building C object libdivsufsort-2.0.1/lib/CMakeFiles/divsufsort.dir/utils.o
Linking C static library libdivsufsort.a
[ 12%] Built target divsufsort
Scanning dependencies of target Sibelia
[ 16%] Building CXX object CMakeFiles/Sibelia.dir/sibelia.cpp.o
In file included from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/file.h:56:0,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/score/score_matrix.h:40,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/score.h:48,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/align.h:44,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/postprocessor.h:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/sibelia.cpp:8:
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/file/file_generated_forwards.h:927:66: error: invalid abstract return type ‘seqan::FileFormat<TFile, TData, TMeta, void>’
 template <typename TFile, typename TData, typename TMeta> inline FileFormat<TFile, TData, TMeta, void> guessFileFormat(
                                                                  ^
In file included from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/file.h:84:0,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/score/score_matrix.h:40,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/score.h:48,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/align.h:44,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/postprocessor.h:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/sibelia.cpp:8:
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/file/file_format.h:143:8: note:   because the following virtual functions are pure within ‘seqan::FileFormat<TFile, TData, TMeta, void>’:
 struct FileFormat<TFile, TData, TMeta, void>
        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/file/file_format.h:154:2: note:     virtual void* seqan::FileFormat<TFile, TData, TMeta, void>::formatID_() const
  formatID_() const = 0;
  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/file/file_format.h:157:2: note:     virtual void seqan::FileFormat<TFile, TData, TMeta, void>::read_(TFile&, TData&) const
  read_(TFile & file, TData & data) const = 0;
  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/file/file_format.h:159:2: note:     virtual void seqan::FileFormat<TFile, TData, TMeta, void>::read_(TFile&, TData&, seqan::FileFormat<TFile, TData, TMeta, void>::TSize) const
  read_(TFile & file, TData & data, TSize limit) const = 0;
  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/file/file_format.h:162:2: note:     virtual void seqan::FileFormat<TFile, TData, TMeta, void>::readMeta_(TFile&, TMeta&) const
  readMeta_(TFile & file, TMeta & meta) const = 0;
  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/file/file_format.h:165:2: note:     virtual void seqan::FileFormat<TFile, TData, TMeta, void>::goNext_(TFile&) const
  goNext_(TFile & file) const = 0;
  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/file/file_format.h:168:2: note:     virtual seqan::FileFormat<TFile, TData, TMeta, void>::TSize seqan::FileFormat<TFile, TData, TMeta, void>::length_(TFile&) const
  length_(TFile & file) const = 0;
  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/file/file_format.h:171:2: note:     virtual void seqan::FileFormat<TFile, TData, TMeta, void>::write_(TFile&, TData&) const
  write_(TFile & file, TData & data) const = 0;
  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/seqan/file/file_format.h:173:2: note:     virtual void seqan::FileFormat<TFile, TData, TMeta, void>::write_(TFile&, TData&, TMeta&) const
  write_(TFile & file, TData & data, TMeta & meta) const = 0;
  ^
In file included from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/buckets.hpp:15:0,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/table.hpp:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/equivalent.hpp:14,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_set.hpp:17,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered_set.hpp:16,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/common.h:35,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/fasta.h:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/postprocessor.h:13,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/sibelia.cpp:8:
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:437:55: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <typename T, typename ValueType, typename... Args>
                                                       ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:561:39: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         template <typename T, typename... Args>
                                       ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:565:62: warning: variadic templates only available with -std=c++11 or -std=gnu++11
             construct(Alloc& a, T* p, BOOST_FWD_REF(Args)... x)
                                                              ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:570:39: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         template <typename T, typename... Args>
                                       ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:574:60: warning: variadic templates only available with -std=c++11 or -std=gnu++11
             construct(Alloc&, T* p, BOOST_FWD_REF(Args)... x)
                                                            ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:770:51: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <typename Alloc, typename T, typename... Args>
                                                   ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:772:32: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         BOOST_FWD_REF(Args)... args)
                                ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:944:51: warning: variadic templates only available with -std=c++11 or -std=gnu++11
     template <typename Alloc, typename T, typename... Args>
                                                   ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:946:32: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         BOOST_FWD_REF(Args)... args)
                                ^
In file included from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/buckets.hpp:15:0,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/table.hpp:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/equivalent.hpp:14,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_set.hpp:17,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered_set.hpp:16,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/common.h:35,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/fasta.h:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/postprocessor.h:13,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/sibelia.cpp:8:
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:90:50: warning: variadic templates only available with -std=c++11 or -std=gnu++11
 #define BOOST_UNORDERED_EMPLACE_TEMPLATE typename... Args
                                                  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/buckets.hpp:344:19: note: in expansion of macro ‘BOOST_UNORDERED_EMPLACE_TEMPLATE’
         template <BOOST_UNORDERED_EMPLACE_TEMPLATE>
                   ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:91:61: warning: variadic templates only available with -std=c++11 or -std=gnu++11
 #define BOOST_UNORDERED_EMPLACE_ARGS BOOST_FWD_REF(Args)... args
                                                             ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/buckets.hpp:345:35: note: in expansion of macro ‘BOOST_UNORDERED_EMPLACE_ARGS’
         void construct_with_value(BOOST_UNORDERED_EMPLACE_ARGS)
                                   ^
In file included from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/equivalent.hpp:15:0,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_set.hpp:17,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered_set.hpp:16,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/common.h:35,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/fasta.h:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/postprocessor.h:13,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/sibelia.cpp:8:
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/extract_key.hpp:60:24: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         template <class... Args>
                        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/extract_key.hpp:61:42: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         static no_key extract(Args const&...)
                                          ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/extract_key.hpp:111:24: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         template <class... Args>
                        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/extract_key.hpp:112:42: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         static no_key extract(Args const&...)
                                          ^
In file included from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/buckets.hpp:15:0,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/table.hpp:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/equivalent.hpp:14,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_set.hpp:17,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered_set.hpp:16,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/common.h:35,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/fasta.h:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/postprocessor.h:13,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/sibelia.cpp:8:
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:90:50: warning: variadic templates only available with -std=c++11 or -std=gnu++11
 #define BOOST_UNORDERED_EMPLACE_TEMPLATE typename... Args
                                                  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/equivalent.hpp:459:19: note: in expansion of macro ‘BOOST_UNORDERED_EMPLACE_TEMPLATE’
         template <BOOST_UNORDERED_EMPLACE_TEMPLATE>
                   ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:91:61: warning: variadic templates only available with -std=c++11 or -std=gnu++11
 #define BOOST_UNORDERED_EMPLACE_ARGS BOOST_FWD_REF(Args)... args
                                                             ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/equivalent.hpp:460:26: note: in expansion of macro ‘BOOST_UNORDERED_EMPLACE_ARGS’
         iterator emplace(BOOST_UNORDERED_EMPLACE_ARGS)
                          ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:90:50: warning: variadic templates only available with -std=c++11 or -std=gnu++11
 #define BOOST_UNORDERED_EMPLACE_TEMPLATE typename... Args
                                                  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/unique.hpp:374:19: note: in expansion of macro ‘BOOST_UNORDERED_EMPLACE_TEMPLATE’
         template <BOOST_UNORDERED_EMPLACE_TEMPLATE>
                   ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:91:61: warning: variadic templates only available with -std=c++11 or -std=gnu++11
 #define BOOST_UNORDERED_EMPLACE_ARGS BOOST_FWD_REF(Args)... args
                                                             ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/unique.hpp:375:32: note: in expansion of macro ‘BOOST_UNORDERED_EMPLACE_ARGS’
         emplace_return emplace(BOOST_UNORDERED_EMPLACE_ARGS)
                                ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:90:50: warning: variadic templates only available with -std=c++11 or -std=gnu++11
 #define BOOST_UNORDERED_EMPLACE_TEMPLATE typename... Args
                                                  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/unique.hpp:397:19: note: in expansion of macro ‘BOOST_UNORDERED_EMPLACE_TEMPLATE’
         template <BOOST_UNORDERED_EMPLACE_TEMPLATE>
                   ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:91:61: warning: variadic templates only available with -std=c++11 or -std=gnu++11
 #define BOOST_UNORDERED_EMPLACE_ARGS BOOST_FWD_REF(Args)... args
                                                             ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/unique.hpp:399:13: note: in expansion of macro ‘BOOST_UNORDERED_EMPLACE_ARGS’
             BOOST_UNORDERED_EMPLACE_ARGS)
             ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:90:50: warning: variadic templates only available with -std=c++11 or -std=gnu++11
 #define BOOST_UNORDERED_EMPLACE_TEMPLATE typename... Args
                                                  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/unique.hpp:431:19: note: in expansion of macro ‘BOOST_UNORDERED_EMPLACE_TEMPLATE’
         template <BOOST_UNORDERED_EMPLACE_TEMPLATE>
                   ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/allocate.hpp:91:61: warning: variadic templates only available with -std=c++11 or -std=gnu++11
 #define BOOST_UNORDERED_EMPLACE_ARGS BOOST_FWD_REF(Args)... args
                                                             ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/detail/unique.hpp:432:45: note: in expansion of macro ‘BOOST_UNORDERED_EMPLACE_ARGS’
         emplace_return emplace_impl(no_key, BOOST_UNORDERED_EMPLACE_ARGS)
                                             ^
In file included from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered_set.hpp:16:0,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/common.h:35,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/fasta.h:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/postprocessor.h:13,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/sibelia.cpp:8:
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_set.hpp:233:24: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         template <class... Args>
                        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_set.hpp:234:66: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         std::pair<iterator, bool> emplace(BOOST_FWD_REF(Args)... args)
                                                                  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_set.hpp:239:24: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         template <class... Args>
                        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_set.hpp:240:70: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         iterator emplace_hint(const_iterator, BOOST_FWD_REF(Args)... args)
                                                                      ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_set.hpp:701:24: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         template <class... Args>
                        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_set.hpp:702:49: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         iterator emplace(BOOST_FWD_REF(Args)... args)
                                                 ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_set.hpp:707:24: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         template <class... Args>
                        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_set.hpp:708:70: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         iterator emplace_hint(const_iterator, BOOST_FWD_REF(Args)... args)
                                                                      ^
In file included from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered_map.hpp:16:0,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/common.h:36,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/fasta.h:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/postprocessor.h:13,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/sibelia.cpp:8:
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_map.hpp:235:24: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         template <class... Args>
                        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_map.hpp:236:66: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         std::pair<iterator, bool> emplace(BOOST_FWD_REF(Args)... args)
                                                                  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_map.hpp:241:24: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         template <class... Args>
                        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_map.hpp:242:70: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         iterator emplace_hint(const_iterator, BOOST_FWD_REF(Args)... args)
                                                                      ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_map.hpp:717:24: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         template <class... Args>
                        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_map.hpp:718:49: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         iterator emplace(BOOST_FWD_REF(Args)... args)
                                                 ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_map.hpp:723:24: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         template <class... Args>
                        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/unordered/unordered_map.hpp:724:70: warning: variadic templates only available with -std=c++11 or -std=gnu++11
         iterator emplace_hint(const_iterator, BOOST_FWD_REF(Args)... args)
                                                                      ^
In file included from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/intrusive/pointer_traits.hpp:26:0,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/slist.hpp:25,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/common.h:37,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/fasta.h:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/postprocessor.h:13,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/sibelia.cpp:8:
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/intrusive/detail/memory_util.hpp:154:42: warning: variadic templates only available with -std=c++11 or -std=gnu++11
    template <template <typename, typename...> class TemplateClass, typename T, typename... Args>
                                          ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/intrusive/detail/memory_util.hpp:154:88: warning: variadic templates only available with -std=c++11 or -std=gnu++11
    template <template <typename, typename...> class TemplateClass, typename T, typename... Args>
                                                                                        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/intrusive/detail/memory_util.hpp:250:33: warning: variadic templates only available with -std=c++11 or -std=gnu++11
 template <template <class, class...> class Ptr, typename T, class... Tn, class U>
                                 ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/intrusive/detail/memory_util.hpp:250:66: warning: variadic templates only available with -std=c++11 or -std=gnu++11
 template <template <class, class...> class Ptr, typename T, class... Tn, class U>
                                                                  ^
In file included from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/detail/utilities.hpp:28:0,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/slist.hpp:26,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/common.h:37,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/fasta.h:10,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/postprocessor.h:13,
                 from /home/assemblers/.local/opt/Sibelia-3.0.5/src/sibelia.cpp:8:
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/allocator_traits.hpp:182:31: warning: variadic templates only available with -std=c++11 or -std=gnu++11
             template <typename... Args>
                               ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/allocator_traits.hpp:183:49: warning: variadic templates only available with -std=c++11 or -std=gnu++11
             rebind_alloc(BOOST_FWD_REF(Args)... args)
                                                 ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/allocator_traits.hpp:280:32: warning: variadic templates only available with -std=c++11 or -std=gnu++11
       template <class T, class ...Args>
                                ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/allocator_traits.hpp:281:69: warning: variadic templates only available with -std=c++11 or -std=gnu++11
       static void construct(Alloc & a, T* p, BOOST_FWD_REF(Args)... args)
                                                                     ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/allocator_traits.hpp:317:34: warning: variadic templates only available with -std=c++11 or -std=gnu++11
          template<class T, class ...Args>
                                  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/allocator_traits.hpp:318:95: warning: variadic templates only available with -std=c++11 or -std=gnu++11
          static void priv_construct(boost::false_type, Alloc &a, T *p, BOOST_FWD_REF(Args) ...args)                   
                                                                                               ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/allocator_traits.hpp:327:34: warning: variadic templates only available with -std=c++11 or -std=gnu++11
          template<class T, class ...Args>
                                  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/allocator_traits.hpp:328:94: warning: variadic templates only available with -std=c++11 or -std=gnu++11
          static void priv_construct(boost::true_type, Alloc &a, T *p, BOOST_FWD_REF(Args) ...args)
                                                                                              ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/allocator_traits.hpp:333:34: warning: variadic templates only available with -std=c++11 or -std=gnu++11
          template<class T, class ...Args>
                                  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/allocator_traits.hpp:334:104: warning: variadic templates only available with -std=c++11 or -std=gnu++11
          static void priv_construct_dispatch2(boost::true_type, Alloc &a, T *p, BOOST_FWD_REF(Args) ...args)
                                                                                                        ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/allocator_traits.hpp:337:34: warning: variadic templates only available with -std=c++11 or -std=gnu++11
          template<class T, class ...Args>
                                  ^
/home/assemblers/.local/opt/Sibelia-3.0.5/src/include/boost/container/allocator_traits.hpp:338:104: warning: variadic templates only available with -std=c++11 or -std=gnu++11
          static void priv_construct_dispatch2(boost::false_type, Alloc &, T *p, BOOST_FWD_REF(Args) ...args)
                                                                                                        ^
CMakeFiles/Sibelia.dir/build.make:54: recipe for target 'CMakeFiles/Sibelia.dir/sibelia.cpp.o' failed
make[2]: *** [CMakeFiles/Sibelia.dir/sibelia.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/Sibelia.dir/all' failed
make[1]: *** [CMakeFiles/Sibelia.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ilyaminkin** [comment]
Hi, can you use binaries: https://sourceforge.net/projects/sibelia-bio/files/ ?

**Comment by SethosII** [comment]
I also get the error `invalid abstract return type` at the same place. I'm using GCC 5.4.0 on a Ubuntu 16.04. What was used to build the binary files?

**Comment by ilyaminkin** [comment]
Some version of GCC 4.7.x if I recall correctly. This compilation error is within an external library, so it may be tricky to fix. I will give it a try though.

**Comment by SethosII** [comment]
Ok, so maybe it's an issue with the default c/c++ standard used, which changed in newer GCC versions and an older standard needs to be made explicit?

**Comment by ilyaminkin** [comment]
@SethosII I made commit, try now please.

**Comment by SethosII** [comment]
@ilyaminkin Tried it and it works with GCC 5.4.0 now. Thank you very much for looking into this!

**Comment by SethosII** [comment]
@ilyaminkin can you also provide a release for the fixed version on github and sourceforge?
